### ISSUE TITLE
This commit removed <?php tag 

### ISSUE THREAD

**Issue by askdkc** [coderflexx/laravel-csv#6]
This commit https://github.com/coderflexx/laravel-csv/commit/209cc877c303f31f16e088f12338acc2a61f639c removed <?php tag. And [this is not right](https://github.com/coderflexx/laravel-csv/pull/5#issuecomment-1262675562), according to @ousid.

So I created  Fix #5

**Comment by ousid** [comment]
Thanks for the PR!

**Comment by askdkc** [comment]
"composer require coderflex/laravel-csv" is now working properly.
Thank you for your quick review!
