### ISSUE TITLE
Published view is not working

### ISSUE THREAD

**Issue by askdkc** [coderflexx/laravel-csv#8]
As I mentioned this [PR](https://github.com/coderflexx/laravel-csv/pull/4), published view is not used properly it seems.

How to reproduce:
1. clone this [laravel-cev-demo repository](https://github.com/coderflexx/laravel-csv-demo)
2. Installing everything by following README instruction
3. Run `php artisan vendor:publish --tag="csv-views"`
4. Edit resources/views/vendor/csv/livewire/tailwindcss/csv-importer.blade.php
5. access http://Local_URL/customers
6. Click Import button but import view is not reflecting the edit you made on csv-importer.blade.php at step 4.

Something wrong with this package.

**Comment by ousid** [comment]
Hey, @askdkc. 
Sorry for the late response, I'll investigate this one today, when I have time.

**Comment by askdkc** [comment]
Hey, @ousid.

It turns out, this problem is not your code but rather it caused by spatie laravel-package-tools' bug.
So I sent [this PR](https://github.com/spatie/laravel-package-tools/pull/69) to spatie, in order to fix this bug.
And after it got merged, your package works fine now.

But you need to change the tag name for publishing the view files (because you are using custom view namespace in your code).

So I created this [PR](https://github.com/coderflexx/laravel-csv/pull/11).

Hope this helps and close this issue!

**Comment by ousid** [comment]
Resolved: https://github.com/coderflexx/laravel-csv/pull/11
